package detect

var primaryMarkers = []struct {
	file  string
	label string
}{
	{"go.mod", "Go"},
	{"Cargo.toml", "Rust"},
	{"pyproject.toml", "Python"},
	{"setup.py", "Python"},
	{"setup.cfg", "Python"},
	{"requirements.txt", "Python"},
	{"Pipfile", "Python"},
	{"pom.xml", "Java"},
	{"build.gradle", "Java"},
	{"build.gradle.kts", "Kotlin"},
	{"*.csproj", "C#"},
	{"*.fsproj", "F#"},
	{"composer.json", "PHP"},
	{"Gemfile", "Ruby"},
	{"mix.exs", "Elixir"},
	{"pubspec.yaml", "Dart"},
	{"CMakeLists.txt", "C/C++"},
	{"flake.nix", "Nix"},
	{"default.nix", "Nix"},
	{"deno.json", "Deno"},
	{"deno.jsonc", "Deno"},
	{"bun.lockb", "Bun"},
	{"bun.lock", "Bun"},
	{"*.cabal", "Haskell"},
	{"stack.yaml", "Haskell"},
	{"rebar.config", "Erlang"},
	{"mix.lock", "Elixir"},
	{"project.clj", "Clojure"},
	{"build.sbt", "Scala"},
	{"*.opam", "OCaml"},
	{"dune-project", "OCaml"},
	{"Package.swift", "Swift"},
	{"*.zig", "Zig"},
	{"build.zig", "Zig"},
}

var secondaryMarkers = []struct {
	file  string
	label string
}{
	{"next.config.js", "Next.js"},
	{"next.config.ts", "Next.js"},
	{"next.config.mjs", "Next.js"},
	{"nuxt.config.js", "Nuxt"},
	{"nuxt.config.ts", "Nuxt"},
	{"svelte.config.js", "Svelte"},
	{"svelte.config.ts", "Svelte"},
	{"astro.config.mjs", "Astro"},
	{"astro.config.ts", "Astro"},
	{"remix.config.js", "Remix"},
	{"vite.config.js", "Vite"},
	{"vite.config.ts", "Vite"},
	{"vite.config.mjs", "Vite"},
	{"angular.json", "Angular"},
	{"solid.config.ts", "Solid"},
	{"electron-builder.yml", "Electron"},
	{"electron-builder.json", "Electron"},
	{"manage.py", "Django"},
	{"Dockerfile", "Docker"},
	{"docker-compose.yml", "Docker"},
	{"docker-compose.yaml", "Docker"},
	{"*.tf", "Terraform"},
	{"*.tfvars", "Terraform"},
	{"ansible.cfg", "Ansible"},
	{"playbook.yml", "Ansible"},
}

var directoryMarkers = []struct {
	dir   string
	label string
}{
	{"node_modules", "Node"},
	{".next", "Next.js"},
	{".nuxt", "Nuxt"},
	{".svelte-kit", "SvelteKit"},
	{".astro", "Astro"},
	{".angular", "Angular"},
	{"vendor", ""},
	{"__pycache__", "Python"},
	{".venv", "Python"},
	{"venv", "Python"},
	{"env", "Python"},
	{"target", ""},
	{".gradle", "Java"},
	{"ios", "Swift"},
	{"android", ""},
	{".terraform", "Terraform"},
	{".ansible", "Ansible"},
}

var extensionMap = map[string]string{
	".go":     "Go",
	".rs":     "Rust",
	".py":     "Python",
	".rb":     "Ruby",
	".php":    "PHP",
	".java":   "Java",
	".kt":     "Kotlin",
	".swift":  "Swift",
	".cs":     "C#",
	".fs":     "F#",
	".cpp":    "C/C++",
	".c":      "C/C++",
	".h":      "C/C++",
	".hpp":    "C/C++",
	".ts":     "TypeScript",
	".tsx":    "TypeScript",
	".js":     "JavaScript",
	".jsx":    "JavaScript",
	".vue":    "Vue",
	".svelte": "Svelte",
	".html":   "HTML",
	".htm":    "HTML",
	".css":    "CSS",
	".scss":   "CSS",
	".sass":   "CSS",
	".less":   "CSS",
	".ex":     "Elixir",
	".exs":    "Elixir",
	".erl":    "Erlang",
	".hs":     "Haskell",
	".clj":    "Clojure",
	".scala":  "Scala",
	".ml":     "OCaml",
	".dart":   "Dart",
	".zig":    "Zig",
	".sh":     "Shell",
	".bash":   "Shell",
	".zsh":    "Shell",
	".fish":   "Shell",
	".pl":     "Perl",
	".pm":     "Perl",
	".tf":     "Terraform",
}

var frameworkDeps = []struct {
	dep   string
	label string
}{
	{"next", "Next.js"},
	{"nuxt", "Nuxt"},
	{"@nuxtjs/composition-api", "Nuxt"},
	{"svelte", "Svelte"},
	{"@sveltejs/kit", "SvelteKit"},
	{"astro", "Astro"},
	{"@remix-run/node", "Remix"},
	{"@remix-run/react", "Remix"},
	{"solid-js", "Solid"},
	{"@solidjs/start", "Solid"},
	{"@angular/core", "Angular"},
	{"vue", "Vue"},
	{"react-native", "React Native"},
	{"expo", "React Native"},
	{"react", "React"},
	{"electron", "Electron"},
	{"express", "Express"},
	{"fastify", "Fastify"},
	{"@nestjs/core", "Nest.js"},
	{"vite", "Vite"},
	{"typescript", "TypeScript"},
	{"django", "Django"},
	{"flask", "Flask"},
	{"fastapi", "FastAPI"},
}

var pythonFrameworkMarkers = []struct {
	name  string
	label string
}{
	{"django", "Django"},
	{"flask", "Flask"},
	{"fastapi", "FastAPI"},
	{"tornado", "Python"},
	{"aiohttp", "Python"},
	{"starlette", "Python"},
}
